name: CI

on:
  push:
    branches:
      - AzureNetworkTesting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        ref: AzureNetworkTesting
          
    - name: Check Path
      run: |
        ls -la
        cat requirements.txt
