name: CI

on:
  push:
    branches:
      - AzureNetworkTesting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Jinja2 Syntax Check
      uses: cotsiosglad/Jinja2SyntaxChecker@v1.0.1
      with:
        directory: ./
        
