name: CI

on:
  push:
    branches:
      - AzureNetworkTesting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clear Cache
      uses: TheRealRyGuy/clear-cache-action@v0.1      
      
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        ref: main
          
    - name: Check Path
      run: |
        ls -la
        cat requirements.txt
